version: "3.8"

services:
  db:
    image: ghcr.io/andres-rojas/explainshell-db
    restart: unless-stopped
  explainshell:
    command: make serve
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db
      - HOST_IP=0.0.0.0
    image: ghcr.io/andres-rojas/explainshell:flask-v1
    restart: unless-stopped
  workspace:
    command: sleep infinity
    depends_on:
      - explainshell
    image: mcr.microsoft.com/devcontainers/base:jammy
    user: vscode
    volumes:
      - ..:/workspace
